import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,useScroll,useTransform,AnimatePresence} from 'framer-motion';
import {ArrowUpRight,Menu,X,Search,ChevronDown,MapPin,Database,BarChart3,Users,Globe2,Sparkles} from 'lucide-react';
import './styles.css';

const sectors=['Agriculture','Business Development & Entrepreneurship','Education','Gender, Child & Social Inclusion','Governance','Land, Natural Resources & Environment','Socio-Economic Livelihood & Engagement','WASH'];
const services=[['Research & M&E','Baseline, endline, impact evaluation, market research, surveys and rigorous field research.'],['Data & Analytics','Data collection, management, analysis, dashboards and evidence systems that turn information into decisions.'],['Organizational Development','Training, capacity building, organizational assessments, gender audits and institutional development.'],['Business Advisory','Business planning, strategic planning, feasibility, market entry and entrepreneurship support.']];
const projects=[['Education','Monitoring & Evaluation','National-scale education evidence programme'],['Governance','Research','Institutional systems and citizen experience study'],['Agriculture','Data & Analytics','Agricultural livelihoods data collection and insight programme'],['WASH','Field Research','Community water and sanitation assessment']];

function App(){
 const [menu,setMenu]=useState(false); const [active,setActive]=useState('All');
 const {scrollYProgress}=useScroll(); const heroY=useTransform(scrollYProgress,[0,.35],[0,-90]);
 const filtered=active==='All'?projects:projects.filter(p=>p[0]===active);
 useEffect(()=>{document.body.style.overflow=menu?'hidden':'';return()=>document.body.style.overflow=''},[menu]);
 return <div>
  <div className="progress" style={{scaleX:scrollYProgress}}/>
  <header className="header"><div className="header-inner"><a className="brand" href="#top"><img src="/logo-full.png"/><span className="brand-dot"/></a><nav>{['About','Services','Sectors','Projects','Insights','Team'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><div className="header-actions"><a className="text-link" href="#opportunities">Opportunities</a><a className="cta small" href="#contact">Let’s talk <ArrowUpRight size={15}/></a><button className="icon-btn mobile-only" onClick={()=>setMenu(true)}><Menu/></button></div></div></header>
  <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="mobile-top"><img src="/logo-full.png"/><button className="icon-btn" onClick={()=>setMenu(false)}><X/></button></div><div className="mobile-links">{['About','Services','Sectors','Projects','Insights','Team','Opportunities','Contact'].map(x=><a key={x} onClick={()=>setMenu(false)} href={'#'+x.toLowerCase()}>{x}<ArrowUpRight size={20}/></a>)}</div></motion.div>}</AnimatePresence>

  <main id="top">
   <section className="hero"><div className="grid-lines"/><motion.div className="hero-inner" style={{y:heroY}}><div className="eyebrow"><span className="pulse"/> Independent research • data • development consulting</div><h1>Evidence that <em>moves</em><br/>decisions forward.</h1><p className="hero-copy">JMK Consulting Group turns complex questions into credible evidence, actionable insight and measurable impact across development, business and public-sector systems.</p><div className="hero-actions"><a className="cta" href="#contact">Start a conversation <ArrowUpRight/></a><a className="ghost" href="#projects">Explore our work <span>↓</span></a></div><div className="hero-meta"><div><span>01</span><strong>Research</strong></div><div><span>02</span><strong>Data & Analytics</strong></div><div><span>03</span><strong>Impact & Development</strong></div></div></motion.div><div className="hero-orbit" aria-hidden="true"><div className="orbit-ring one"/><div className="orbit-ring two"/><div className="orbit-core"><Database size={34}/></div><span className="orb-label o1">FIELD</span><span className="orb-label o2">EVIDENCE</span><span className="orb-label o3">IMPACT</span></div></section>

   <section className="ticker"><div className="ticker-track">RESEARCH <span>◆</span> MONITORING & EVALUATION <span>◆</span> DATA SYSTEMS <span>◆</span> ORGANIZATIONAL DEVELOPMENT <span>◆</span> FIELD RESEARCH <span>◆</span> BUSINESS ADVISORY <span>◆</span></div></section>

   <section className="intro section" id="about"><div className="section-kicker">01 / WHO WE ARE</div><div className="split"><div><h2>Built for complex questions.</h2></div><div><p className="lead">We are a research, monitoring and evaluation, data, organizational development and development consulting firm. Our strength is the bridge between disciplined evidence and practical action.</p><p>From large-scale field studies to institutional assessments, JMK combines local understanding, robust methodology, technology and human insight to help clients see what matters — and what to do next.</p><a className="underlink" href="#services">Discover our approach <ArrowUpRight size={16}/></a></div></div></section>

   <section className="metrics"><div className="metric"><strong>8</strong><span>core sectors</span></div><div className="metric"><strong>360°</strong><span>evidence lifecycle</span></div><div className="metric"><strong>Ghana+</strong><span>regional reach</span></div><div className="metric"><strong>01</strong><span>integrated partner</span></div></section>

   <section className="services section" id="services"><div className="section-kicker">02 / WHAT WE DO</div><div className="section-head"><h2>Capabilities with <em>depth.</em></h2><p>Designed around the full journey from question to evidence to action.</p></div><div className="service-grid">{services.map((s,i)=><motion.article className="service-card" key={s[0]} whileHover={{y:-8}} transition={{type:'spring',stiffness:280,damping:24}}><div className="service-num">0{i+1}</div><div><h3>{s[0]}</h3><p>{s[1]}</p><a href="#contact">View capability <ArrowUpRight size={15}/></a></div></motion.article>)}</div></section>

   <section className="sectors section" id="sectors"><div className="section-kicker">03 / CORE AREAS</div><div className="section-head"><h2>Where evidence meets <em>impact.</em></h2></div><div className="sector-grid">{sectors.map((s,i)=><a className="sector-item" href="#contact" key={s}><span>{String(i+1).padStart(2,'0')}</span><strong>{s}</strong><ArrowUpRight size={19}/></a>)}</div></section>

   <section className="projects section" id="projects"><div className="section-kicker">04 / CORPORATE EXPERIENCE</div><div className="section-head row"><div><h2>Work worth <em>exploring.</em></h2><p>Filter by sector to surface the kind of work you need.</p></div><div className="filters"><button onClick={()=>setActive('All')} className={active==='All'?'active':''}>All</button>{['Education','Governance','Agriculture','WASH'].map(x=><button key={x} onClick={()=>setActive(x)} className={active===x?'active':''}>{x}</button>)}</div></div><div className="project-grid">{filtered.map((p,i)=><motion.article layout className="project-card" key={p.join('-')} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'-40px'}}><div className="project-visual"><div className="noise"/><div className="project-mark">{i+1}</div><span>{p[0]}</span></div><div className="project-body"><div className="project-tag">{p[1]}</div><h3>{p[2]}</h3><a href="#contact">View case study <ArrowUpRight size={15}/></a></div></motion.article>)}</div></section>

   <section className="insights section" id="insights"><div className="section-kicker">05 / KNOWLEDGE HUB</div><div className="insight-feature"><div><span className="tag">DATA STORY</span><h2>Make the evidence impossible to ignore.</h2><p>Thought leadership, project updates, research insights and practical commentary — presented with the clarity decision-makers need.</p><a className="cta" href="#contact">Explore insights <ArrowUpRight/></a></div><div className="data-art"><BarChart3 size={42}/><div className="bars"><i style={{height:'32%'}}/><i style={{height:'58%'}}/><i style={{height:'46%'}}/><i style={{height:'82%'}}/><i style={{height:'68%'}}/><i style={{height:'94%'}}/></div></div></div></section>

   <section className="people section" id="team"><div className="section-kicker">06 / PEOPLE</div><div className="split"><div><h2>Human expertise.<br/><em>Methodological discipline.</em></h2></div><div><p className="lead">A multidisciplinary team across research, data, project management, field operations, gender and social inclusion, finance and administration.</p><div className="people-pills"><span><Users size={15}/> Research</span><span><BarChart3 size={15}/> Data</span><span><Globe2 size={15}/> Field</span><span><Sparkles size={15}/> Strategy</span></div></div></div></section>

   <section className="opps section" id="opportunities"><div className="opps-panel"><div><div className="section-kicker">07 / OPPORTUNITIES</div><h2>Bring your expertise<br/>to the <em>field.</em></h2></div><div><p>Consultants, enumerators and interns can register through a structured talent pipeline built for real project demand.</p><a className="ghost light" href="#contact">See opportunities <ArrowUpRight size={16}/></a></div></div></section>

   <section className="contact section" id="contact"><div className="contact-inner"><div><div className="section-kicker">08 / CONTACT</div><h2>Have a complex problem?<br/><em>Let’s build the evidence.</em></h2></div><form onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@company.com"/></label><label>How can we help?<select><option>Research assignment</option><option>Monitoring & Evaluation</option><option>Data collection</option><option>Business / organizational development</option><option>General enquiry</option></select></label><label>Message<textarea placeholder="Tell us a little about the brief…" rows="4"/></label><button className="cta" type="submit">Send enquiry <ArrowUpRight/></button></form></div></section>
  </main>
  <footer><div className="footer-top"><div><img src="/logo-full.png" className="footer-logo"/><p>Research. Data. Impact.</p></div><div className="footer-nav"><div><strong>Explore</strong><a href="#about">About</a><a href="#services">Services</a><a href="#projects">Projects</a></div><div><strong>Connect</strong><a href="#contact">Contact</a><a href="#opportunities">Opportunities</a><a href="#insights">Insights</a></div></div></div><div className="footer-bottom"><span>© 2026 JMK Consulting Group</span><span>Built around evidence.</span><span>Privacy · Terms</span></div></footer>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
